credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$abcdefghijk1234...
      admin: True
      approved: True
    user1:
      email: user1@example.com
      name: User One
      password: $2b$12$lmnopqrst5678...
      admin: False
      approved: True
preauthorized:
  emails:
    - admin@example.com
cookie:
  name: streamlit-auth
  key: random_key_here
  expiry_days: 30
